### ISSUE TITLE
eefolium

### ISSUE THREAD

**Issue by bextla20** [giswqs/eefolium#4]
Hi

l am trying import eefolium by GEE. but it shows **ModuleNotFoundError: No module named 'geemap.eefolium'**

import geemap
Map = geemap.Map(center=[40,-100], zoom=4)
Map

import geemap.eefolium as emap
Map = emap.Map(center=[40,-100], zoom=4)
Map

![image](https://user-images.githubusercontent.com/62169942/235649069-88bf4af1-2531-4181-979b-32112797286b.png)

**Comment by giswqs** [comment]
Try `import eefolium`
