### ISSUE TITLE
cogeo.xyz deprecation 

### ISSUE THREAD

**Issue by vincentsarago** [giswqs/eefolium#5]
Hi,
Just to let you know that the https://cogeo.xyz/ website and api are deprecated and will be teared down in couple days. Please make sure to switch to https://titiler.xyz/ (Developmentseed demonstration endpoints) or deploy your own tile server (https://developmentseed.org/titiler/)

https://github.com/giswqs/eefolium/blob/f4ba02fe442cd5cd8e839a142bb905fb24686337/eefolium/eefolium.py#L467

**Comment by giswqs** [comment]
@vincentsarago Thanks for the notice. This package is longer being updated. I did not realize that it still uses the old titiler endpoint. I am fixing it in #6
