### ISSUE TITLE
No split map function

### ISSUE THREAD

**Issue by Awumboro** [giswqs/eefolium#7]
* eefolium version:
* Python version: 0.2.0
* Operating System: Windows 11

### Description
I was trying to implement a split_map function using eefolium as described in the documentation similar to what is implemented on geemap. 
Although the documentation on eefolium indicates there is a ```Map.split_map( )``` function, this does not seem to be the case as I keep receiving an AttributeError: ```Map object has no attribute 'split_map'```. 

I think it will be a great idea to include the implementation of a split_map function similar to what is available on geemap. I am especially using eefolium over geemap because it allows me to serialize the map object using; ```Map._repr_html_()``` function which is an important feature for me.

### What I Did

```
class_vis_params = {'palette': ['#008000', ' #0000ff', ' #ff0000', ' #ffff00'], 'min': 1.0, 'max': 4.0, 'opacity': 1.0,}
from eefolium import Map
Map = eefolium.Map()

left_layer = geemap.ee_tile_layer(lulc_start, class_vis_params, "lulc_start")
right_layer = geemap.ee_tile_layer(lulc_end, class_vis_params, "lulc_end")

Map.split_map(left_layer, right_layer)

```
### Crash
```
Crash:
AttributeError                            Traceback (most recent call last)
Cell In[54], line 8
      5 left_layer = geemap.ee_tile_layer(lulc_start, class_vis_params, "lulc_start")
      6 right_layer = geemap.ee_tile_layer(lulc_end, class_vis_params, "lulc_end")
----> 8 Map.split_map(left_layer, right_layer)
     10 Map

AttributeError: 'Map' object has no attribute 'split_map'
```

**Comment by giswqs** [comment]
This package is no longer being maintained. Use geemap instead 

https://geemap.org/notebooks/103_split_control/
